- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: "http://{{inventory_hostname}}"
      return_content: yes
      http_agent: gpte-ansible-training
      status_code:
        - -1
        - 200
    register: web_check
    ignore_errors: yes

  - name: "Fail if 'Ansible has done its job' is not in the page content"
    fail:
      msg: Page content incorrect
    when: "'Ansible has done its job' not in item['content']"
    loop: "{{web_check['results']}}"
    loop_control:
      label: "{{item['url']}}"
