- name: Add dynamic host for workstation
  hosts: localhost
  gather_facts: no
  tasks:
    - add_host:
        hostname: workstation
        ansible_host: "workstation-{{lookup('env', 'OSP_GUID')}}.rhpds.opentlc.com"
        ansible_ssh_private_key_file: "~/.ssh/openstack.pem"
        ansible_ssh_user: cloud-user

- hosts: workstation
  become: yes
  gather_facts: no
  roles:
    - role: osp-servers
      vars:
        stack_state: present
