- name: Add dynamic host for workstation
  hosts: localhost
  gather_facts: no
  tasks:
    - add_host:
        hostname: workstation
        ansible_host: "workstation-{{lookup('env', 'OSP_GUID')}}.rhpds.opentlc.com"
        ansible_ssh_private_key_file: "~/.ssh/openstack.pem"
        ansible_ssh_user: cloud-user
      when: lookup('env', 'OSP_GUID') is defined

- hosts: workstation
  gather_facts: no
  become: yes
  roles:
    - osp-instance-delete
