- hosts: workstation
  gather_facts: false
  force_handlers: true
  tags: osp.smoke
  tasks:
  - name: OpenStack servers
    os_server_info:
     cloud: ospcloud
     server: 'frontend'
    register: openstack_info

  - name: Check website
    uri:
      url: "http://{{item['public_v4']}}"
      return_content: yes
      http_agent: gpte-ansible-training
      status_code:
        - -1
        - 200
    loop: "{{openstack_info['openstack_servers']}}"
    loop_control:
      label: "{{item['name']}}"
    register: web_check
    ignore_errors: yes

  - name: Check HTTP GET results
    notify: Decom QA
    debug:
      msg: "{{item['item']['name']}} -> Status Code: {{item['status']}}"
    changed_when: item['status'] != 200
    loop: "{{web_check['results']}}"
    loop_control:
      label: "{{item['url']}}"

  - name: Check for content
    notify: Decom QA
    debug:
      msg: "Webpage did not correctly load"
    changed_when: "'Ansible has done its job' not in item['content']"
    loop: "{{web_check['results']}}"
    loop_control:
      label: "{{item['url']}}"

  post_tasks:
  - name: "Decom QA compute"
    when: rollback is defined
    include_role:
      name: osp-instance-delete
  - name: Fail if rolledback
    when: rollback is defined
    fail:
      msg: QA checkout failed

  handlers:
    - name: Decom QA
      set_fact:
        rollback: True
