---
# tasks file for osp.security
- name: Create Security Group Apps
  os_security_group:
    cloud: ospcloud
    state: present
    name: apps
    description: ports_open

- name: Create Security Group Rule Apps
  os_security_group_rule:
    cloud: ospcloud
    security_group: apps
    protocol: tcp
    port_range_min: "{{ item['port'] }}"
    port_range_max: "{{ item['port'] }}"
    remote_ip_prefix: "{{ item['ip_prefix'] }}"
  loop: "{{ sec_group['apps'] }}"

- name: Create Security Group Frontend
  os_security_group:
    cloud: ospcloud
    state: present
    name: frontend
    description: ports_open

- name: Create Security Group Rule Frontend
  os_security_group_rule:
    cloud: ospcloud
    security_group: frontend
    protocol: tcp
    port_range_min: "{{ item['port'] }}"
    port_range_max: "{{ item['port'] }}" 
    remote_ip_prefix: "{{ item['ip_prefix'] }}"
  loop: "{{ sec_group['frontend'] }}"
 
- name: Create Security Group DB
  os_security_group:
    cloud: ospcloud
    state: present
    name: db
    description: ports_open

- name: Create Security Group Rule DB
  os_security_group_rule:
    cloud: ospcloud
    security_group: db
    protocol: tcp
    port_range_min: "{{ item['port'] }}"
    port_range_max: "{{ item['port'] }}" 
    remote_ip_prefix: "{{ item['ip_prefix'] }}"
  loop: "{{ sec_group['db'] }}"
...
