---
# vars file for roles/osp-lab

osp_networks:
  # Public Facing Network   
  external:
    cloud_name: ospcloud
    network_name: ext_network
    subnet_name: ext_subnet
    cidr_network: "10.10.10.0/24"
    state: present
    external: true


  # Private Facing Network   
  internal:
    cloud_name: ospcloud
    network_name: int_network
    subnet_name: int_subnet
    cidr_network: "20.20.20.0/24"
    state: present
    external: false

  # Public Facing Router connecting the two networks
osp_router:
  router:
    cloud_name: ospcloud
    state: present
    name: router
    network: ext_network

sec_group:
  apps:
    - { port: '8080', ip_prefix: '0.0.0.0/0' }
    - { port: '22', ip_prefix: '0.0.0.0/0' }
  frontend:
    - { port: '80', ip_prefix: '0.0.0.0/0' }
    - { port: '443', ip_prefix: '0.0.0.0/0' }
    - { port: '22', ip_prefix: '0.0.0.0/0' }
  db:
    - { port: '5432', ip_prefix: '20.20.20.0/24' }
    - { port: '22', ip_prefix: '0.0.0.0/0' }
...
